# pandas study
2021-06-13<br>
판다스 기초<br>
시리즈, 데이터프레임

In [24]:
# import

import pandas as pd
import numpy as np

### Series
https://pandas.pydata.org/docs/reference/api/pandas.Series.html?highlight=series#pandas.Series

In [34]:
# pd.Series parameters

?pd.Series

# pd.Series(
#     data=None,
#     index=None,
#     dtype=None,
#     name=None,
#     copy=False,
#     fastpath=False,
# )

In [91]:
# Series 생성
# list, dictionary, 1D array를 이용해 생성가능
# 2D array부터는 생성이 불가능함

# 1D aray
sr = pd.Series(np.arange(0, 5, 1), 
               dtype = "int32",
               name = "1D array",   # Series name
               index = list("abcde"))
print(sr)
print()


# 2D array
# ValueError: Data must be 1-dimensional
# sr = pd.Series(np.arange(0, 10, 1).reshape(2, -1))


# Dictionary
sr = pd.Series({"a" : 10, "b" : 20, "c" : 30})
print(type(sr))
print(sr)

a    0
b    1
c    2
d    3
e    4
Name: 1D array, dtype: int32

<class 'pandas.core.series.Series'>
a    10
b    20
c    30
dtype: int64


In [58]:
# copy test

# copy = True
# copy = Ture일 때, 원본 데이터와 시리즈 데이터의 변화 비교
print("copy true")
print()

# 원본데이터 sr_dic, sr_dic을 시리즈 형태로 변화시킨 sr
sr_dic = {"a" : 10, "b" : 20, "c" : 30}
sr = pd.Series(sr_dic, name = "cp_test", copy = True)
print(f"sr :\n{sr}")
print("sr_dic :\n", sr_dic)
print("-"*10)

# sr_dic에 데이터의 변화가 발생할 때, sr의 변화
print('sr_dic["a"] * 10\n')
sr_dic["a"] *= 10
print(f"sr :\n{sr}")
print("sr_dic :", sr_dic)
print("-"*10)
# 변화 X

# sr에 변화가 있을 때, sr_dic의 변화
print("sr[\"b\"] * 10\n")
sr["b"] *= 10
print("sr :", sr)
print("sr_dic :", sr_dic)
# 변화 X


print("-"*50)


# copy = False
# copy = False 일 때, 데이터의 변화 비교
print("copy False")
print()

# 딕셔너리, 시리즈 생성
sr_dic = {"a" : 10, "b" : 20, "c" : 30}
sr = pd.Series(sr_dic, name = "cp_test", copy = False)
print(f"sr :\n{sr}")
print("sr_dic :\n", sr_dic)
print("-"*10)

# sr_dic의 변화에 따른 sr의 변화
print('sr_dic["a"] * 10\n')
sr_dic["a"] *= 10
print(f"sr :\n{sr}")
print("sr_dic :", sr_dic)
print("-"*10)
# 변화 X

# sr의 변화에 따른 sr_dic의 변화
print("sr[\"b\"] * 10\n")
sr["b"] *= 10
print(f"sr :\n{sr}")
print("sr_dic :", sr_dic)
# 변화 X


### 결론
# 예상으로는 from copy import copy에서 copy를 사용하는것과 같은 이유로 카피하는것이라고 생각했었음
# 하지만 결과를 보니 카피 하는것과 하지 않는것에 뭔 차이있는건지는 모르겠음
# 설명상으로는 데이터를 카피한다고 하는데
# 카피 한거랑 안한거랑 데이터의 변화는 없는게 아닐까 싶음
# 둘 다 원본에 변화가 없음

copy true

sr :
a    10
b    20
c    30
Name: cp_test, dtype: int64
sr_dic :
 {'a': 10, 'b': 20, 'c': 30}
----------
sr_dic["a"] * 10

sr :
a    10
b    20
c    30
Name: cp_test, dtype: int64
sr_dic : {'a': 100, 'b': 20, 'c': 30}
----------
sr["b"] * 10

sr : a     10
b    200
c     30
Name: cp_test, dtype: int64
sr_dic : {'a': 100, 'b': 20, 'c': 30}
--------------------------------------------------
copy False

sr :
a    10
b    20
c    30
Name: cp_test, dtype: int64
sr_dic :
 {'a': 10, 'b': 20, 'c': 30}
----------
sr_dic["a"] * 10

sr :
a    10
b    20
c    30
Name: cp_test, dtype: int64
sr_dic : {'a': 100, 'b': 20, 'c': 30}
----------
sr["b"] * 10

sr :
a     10
b    200
c     30
Name: cp_test, dtype: int64
sr_dic : {'a': 100, 'b': 20, 'c': 30}


In [29]:
# index, value 추출
# index값과 value값만 추출

print(sr.index)
print(sr.values)

Index(['a', 'b', 'c'], dtype='object')
[10 20 30]


In [100]:
# 원소 선택
# 문자 인덱스, 숫자 인덱스 둘 다 접근 가능

# 문자인덱스, 숫자 인덱스
print(sr[0])
print(sr["a"])
print()

# 범위 지정
print(sr[0:2])
print(sr["a":"c"])
# 숫자 인덱스는 끝으로 지정한 인덱스 이전까지 출력하며
# 문자 인덱스는 끝으로 지정한 인덱스까지 출력함
print()

# -1 인덱스
print(sr[-1])

10
10

a    10
b    20
dtype: int64
a    10
b    20
c    30
dtype: int64

30


In [103]:
# Series attribute

# 위쪽 URL 참조
# 사용할 수 있는 attribute, method 등이 적혀있음

### DataFrame
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html?highlight=dataframe#pandas.DataFrame

In [92]:
# pd.DataFrame parameters

?pd.DataFrame

# pd.DataFrame(
#     data=None,
#     index: 'Optional[Axes]' = None,
#     columns: 'Optional[Axes]' = None,
#     dtype: 'Optional[Dtype]' = None,
#     copy: 'bool' = False,
# )

In [98]:
# 데이터프레임 생성

df = pd.DataFrame(np.arange(0, 15, 1).reshape(3, -1), 
             index = list("abc"), columns = list("vwxyz"), 
             dtype = "object")
# DataFrame은 name 지정 불가

print(df)
print(type(df))

    v   w   x   y   z
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
<class 'pandas.core.frame.DataFrame'>


In [99]:
# 인덱스, 값(value) 추출
# DataFrame attribute index, values

print(df.index)
print(df.values)

Index(['a', 'b', 'c'], dtype='object')
[[0 1 2 3 4]
 [5 6 7 8 9]
 [10 11 12 13 14]]


In [ ]:
# 행/열 인덱스 이름 변경

df.rename()